# Generated by Django 5.0 on 2023-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.PositiveIntegerField()),
                ('owner_first_name', models.CharField(max_length=50)),
                ('owner_last_name', models.CharField(max_length=50)),
                ('inhabitants_nr', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('cold_water_index', models.PositiveIntegerField(default=0)),
                ('total_debt', models.IntegerField(default=0)),
            ],
        ),
    ]
