# Generated by Django 5.0 on 2024-01-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartament',
            name='total_debt',
            field=models.FloatField(default=0.0),
        ),
    ]
